import { Component, OnInit } from '@angular/core';
import { Answers } from './answers.model';

@Component({
  selector: 'app-lyceum',
  templateUrl: './lyceum.component.html',
  styleUrls: ['./lyceum.component.scss']
})
export class LyceumComponent implements OnInit {

  searchValue: any;
  tab: Answers[] = [];
  filteredTab: Answers[] = [];

  constructor() { }

  ngOnInit(): void {
    this.tab.push(new Answers('Quel astronome a proposé la théorie héliocentrique au XVIe siècle ?', 'Nicolaus Copernicus'));
    this.tab.push(new Answers('Le drapeau de quel pays détient le record mondial du plus ancien drapeau national utilisé en permanence ?', 'Danemark'));
    this.tab.push(new Answers('Quel gaz compose plus de 90 % de l\'atmosphère de Mars ?', 'Gaz carbonique'));
    this.tab.push(new Answers('Parmi les compétences suivantes, laquelle ne fait PAS partie des compétences de Lohar ?', 'Anéantissement total'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est pas King Skill ?', 'Le soulagement'));
    this.tab.push(new Answers('Qui a eu l\'idée de « Troy » ?', 'Ulysse'));
    this.tab.push(new Answers('Lequel des noms suivants est un autre nom pour la "peste noire" qui a fait rage à travers l\'Europe à la fin du Moyen Âge ?', 'Yersinia pestis'));
    this.tab.push(new Answers('Lequel des jus suivants est contenu dans le cocktail classique "Bloody Mary" ?', 'Jus de tomate'));
    this.tab.push(new Answers('Dans quelle ville se trouve la statue danoise de la Petite Sirène ?', 'Copenhague'));
    this.tab.push(new Answers('Quel est le premier livre de stratégie militaire connu de la Chine ?', '"L\'art de la guerre" de Sun Tzu'));
    this.tab.push(new Answers('Dans la mythologie grecque, comment s\'appelait le chien à trois têtes d\'Hadès qui gardait les portes des Enfers ?', 'Cerbère'));
    this.tab.push(new Answers('Fondateur d\'Edo Bakufu', 'Tokugawa Ieyasu'));
    this.tab.push(new Answers('Mesure officielle Martin Luther', 'Édit de Worms'));
    this.tab.push(new Answers('Quel était un phare construit après que la Macédoine ait conquis l\'Égypte et perdu les sept merveilles du monde antique ?', 'Le phare d\'Alexandrie'));
    this.tab.push(new Answers('Qui était le dernier empereur de toute la Russie ?', 'Nicolas II'));
    this.tab.push(new Answers('Quelle est la beauté qui aurait été la cause de la guerre de Troie ?', 'Hélène'));
    this.tab.push(new Answers('Les humanistes du Nord comme Erasmus étaient surtout connus pour quoi ?', 'Intérêt pour la religion et la forme sociale'));
    this.tab.push(new Answers('Quel psychologue allemand a découvert la courbe d\'oubli du cerveau humain ?', 'Hermann Ebbinghaus'));
    this.tab.push(new Answers('Quel est le rapport de conversion des ampères (A) en milliampères (mA) ?', '1/1000'));
    this.tab.push(new Answers('Lequel des éléments suivants Desiderius Erasmus et Thomas More avaient-ils en commun ?', 'Tous deux étaient considérés comme des humanistes'));
    this.tab.push(new Answers('Qui a le premier mis en place le calendrier julien à Rome ?', 'Jules César'));
    this.tab.push(new Answers('Laquelle des îles suivantes est la plus grande île du monde ?', 'Groenland'));
    this.tab.push(new Answers('Quel commandant a signé un traité de paix avec Saladin en 1192 ?', 'Richard I'));
    this.tab.push(new Answers('Qui a été la première femme humaine créée par Héphaïstos dans la mythologie grecque ?', 'Pandore'));
    this.tab.push(new Answers('Quel commandant était chargé de capturer Constantinople à l\'âge de 21 ans ?', 'Mehmed II'));
    this.tab.push(new Answers('Lequel des fruits suivants, connu sous le nom de "pêche loup", a été considéré à tort comme toxique ?', 'Tomates'));
    this.tab.push(new Answers('Lequel des éléments suivants était également connu sous le nom d\'Empire romain d\'Orient ?', 'empire Byzantin'));
    this.tab.push(new Answers('Lequel des rois français suivants était connu sous le nom de Roi Soleil ?', 'Louis XIV'));
    this.tab.push(new Answers('Quel inventeur a construit la première locomotive électrique au monde en 1837 ?', 'Robert Davidson'));
    this.tab.push(new Answers('Quel type de lieux saints accorde des bonus d\'attaque aux troupes ?', 'Autel de la Flamme'));
    this.tab.push(new Answers('Lequel des éléments suivants ne peut PAS être trouvé dans les boutiques de l\'Alliance ?', 'Clé d\'or'));
    this.tab.push(new Answers('Quel est le surnom de Bélisaire ?', 'Le dernier des romains'));
    this.tab.push(new Answers('Quel roi de pays européen a financé la célèbre expédition de Christophe Colomb ?', 'Espagne'));
    this.tab.push(new Answers('Du XVIIe au XIXe siècle, le royaume de Prusse était principalement dans quel pays moderne', 'Allemagne'));
    this.tab.push(new Answers('À quel ordre de mammifères appartiennent les suidés ?', 'Artiodactyles'));
    this.tab.push(new Answers('Qui était considéré comme le prototype du roi de cœur au poker ?', 'Charlemagne'));
    this.tab.push(new Answers('Qu\'a fait Spartacus en tant qu\'esclave avant de mener la plus grande rébellion d\'esclaves de la Rome antique ?', 'Un gladiateur'));
    this.tab.push(new Answers('Qui a proposé l\'idée philosophique du « je pense, donc je suis » ?', 'Descartes'));
    this.tab.push(new Answers('Laquelle des espèces marines suivantes existe depuis le plus longtemps ?', 'Nautile'));
    this.tab.push(new Answers('Quel pays a offert la Statue de la Liberté au peuple américain ?', 'France'));
    this.tab.push(new Answers('Lequel des physiciens suivants est né le jour anniversaire de la mort de Galileo Galilei et est décédé le jour anniversaire de la naissance d\'Albert Einstein ?', 'Stephen Hawking'));
    this.tab.push(new Answers('Qui était appelé « Napoléon du crime » dans certaines des histoires de Sherlock Holmes ?', 'Professeur Moriarty'));
    this.tab.push(new Answers('Quel bâtiment a été construit à l\'origine à Londres pour abriter la grande exposition de l\'industrie des travaux de toutes les nations qui s\'est tenue en 1851 ?', 'Le palais de cristal'));
    this.tab.push(new Answers('Lequel des éléments suivants a été construit sur l\'ordre de Shah Jahan à la mémoire de sa femme Mumtaz Mahal ?', 'Taj Mhal'));
    this.tab.push(new Answers('combien de fois le caractère 1 est-il utilisé lorsque vous écrivez du numéro 1 au numéro 99 ?', '20'));
    this.tab.push(new Answers('Dans quel pays les guerres carlistes ont-elles eu lieu au XIXe siècle ?', 'Espagne'));
    this.tab.push(new Answers('Quelle guerre a opposé les maisons britanniques de Lancaster et d\'York pour le trône d\'Angleterre ?', 'La guerre des roses'));
    this.tab.push(new Answers('Un apport insuffisant de quel élément peut provoquer une thyromégalie ?', 'Iode'));
    this.tab.push(new Answers('Mesure officielle Martin Luther', 'Régime de vers'));
    this.tab.push(new Answers('Quel monarque français était connu sous le nom de Saint Louis ?', 'Louis IX'));
    this.tab.push(new Answers('Quel pays d\'Asie chevauche l\'ancien empire parthe ?', 'L\'Iran'));
    this.tab.push(new Answers('Quel est le matériau le plus doux connu de l\'humanité ?', 'Talc'));
    this.tab.push(new Answers('Lequel des personnages suivants était un Chevalier de la Table Ronde ?', 'Lancelot'));
    this.tab.push(new Answers('Les trois royaumes de Corée où Baekje, Silla et ?', 'Goguryeo'));
    this.tab.push(new Answers('Lequel des éléments suivants est une source d\'énergie non renouvelable (telle que le charbon, le pétrole ou le gaz naturel) ?', 'Combustibles fossiles'));
    this.tab.push(new Answers('Parmi les propositions suivantes, laquelle est une source d\'énergie alternative basée sur la division d\'atomes lourds en atomes plus légers pour libérer de l\'énergie ?', 'Énergie nucléaire'));
    this.tab.push(new Answers('Quelle guerre a mis fin au règne de la maison Plantagenêt et a commencé le règne des Tudors en Angleterre ?', 'La guerre des roses'));
    this.tab.push(new Answers('Quel commandant s\'appelle l\'hydromel de la mort ?', 'Sarka'));
    this.tab.push(new Answers('Laquelle de ces ressources n\'est pas une ressource naturelle ?', 'Vêtements'));
    this.tab.push(new Answers('Les guerres puniques ont été menées par la Rome antique et quel autre empire antique ?', 'Carthage antique'));
    this.tab.push(new Answers('Qui était la dernière femme pharaon de la dynastie des Ptolémée ?', 'Cléopâtre VII'));
    this.tab.push(new Answers('Raphaël est surtout connu pour sa création dont laquelle parmi les suivantes ?', 'École d\'Athènes'));
    this.tab.push(new Answers('Combien de phases y a-t-il dans l\'événement The Mightiest Governor ?', '5'));
    this.tab.push(new Answers('Quel commandant est connu comme le chef de guerre de Kamakura ?', 'Minamoto no Yoshitsune'));
    this.tab.push(new Answers('Lequel de ces éléments est utilisé pour rallier les troupes de l\'alliance ?', 'Château'));
    this.tab.push(new Answers('Quel est le niveau le plus élevé qu\'un hôtel de ville peut atteindre dans Rise of Kingdoms ?', '25'));
    this.tab.push(new Answers('Quel pays a lancé la tradition de la journée de travail de 8 heures ?', 'Royaume-Uni'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'a PAS été inventé en Chine ?', 'Sismographes'));
    this.tab.push(new Answers('Quel pays n\'est pas en Europe ?', 'Egypte'));
    this.tab.push(new Answers('Lequel des commandants suivants excelle dans l\'attaque des villes ennemies ?', 'César'));
    this.tab.push(new Answers('Alors que Gutenberg a introduit l\'imprimerie en Europe, son invention a été influencée par quel pays, le premier à développer un type mobile ?', 'Chine'));
    this.tab.push(new Answers('Les quatre principales variétés de Guzheng dans la Chine ancienne étaient le Haozhong, le Luqi, le Jiaowei et le... ?', 'Raoliang'));
    this.tab.push(new Answers('Parmi les compétences suivantes, laquelle ne fait PAS partie des compétences d\'El Cid ?', 'Chevalerie'));
    this.tab.push(new Answers('Avec qui Minamoto no Yoshitsune a-t-il levé une armée pour combattre Taira no Kiyomori ?', 'Minamoto no Yoritomo'));
    this.tab.push(new Answers('De quelle couleur est la peau d\'un ours polaire ?', 'Le noir'));
    this.tab.push(new Answers('Les Égyptiens fabriquaient du papier à partir de quel matériau ?', 'Papyrus'));
    this.tab.push(new Answers('Les différences entre une espèce, comme différents becs d\'oiseaux, sont appelées', 'Variantes'));
    this.tab.push(new Answers('Quelle est la longueur d\'un marathon en kilomètres ?', '42.2 Km'));
    this.tab.push(new Answers('Quelle partie du cerveau l\'alcool affectera-t-il ?', 'Le Cervelet'));
    this.tab.push(new Answers('Quel est le bonus de santé des troupes que vous pouvez obtenir d\'un hôpital entièrement amélioré ?', '0,01'));
    this.tab.push(new Answers('A quoi servent les Livres d\'Alliance ?', 'Améliorer le château'));
    this.tab.push(new Answers('Combien y a-t-il de commandants d\'élite dans le jeu ?', '5'));
    this.tab.push(new Answers('Les trois grands philosophes de la Grèce antique étaient Platon, Aristote et ?', 'Socrate.'));
    this.tab.push(new Answers('Lequel des éléments suivants ne peut pas être trouvé dans un coffre d\'argent à la taverne ?', 'Niv. 3 Tome de connaissance'));
    this.tab.push(new Answers('Quel type d\'unité est fort contre les Archers ?', 'Cavalerie'));
    this.tab.push(new Answers('Quel type d\'unité est fort contre la cavalerie ?', 'Infanterie'));
    this.tab.push(new Answers('Qui est le commandant considéré comme un ennemi de Rome depuis l\'enfance ?', 'Hannibal Barça'));
    this.tab.push(new Answers('Lequel de ces commandants a pu vaincre le grand Charles dans la bataille ?', ''));
    this.tab.push(new Answers('Qui a peint La Cène ?', 'Léonard de Vinci'));
    this.tab.push(new Answers('L\'histoire de l\'Égypte ancienne s\'étend sur combien de royaumes ?', '3 - Ancien, Moyen, Nouveau'));
    this.tab.push(new Answers('Qui est le Roi du Royaume ?', 'Chef de l\'alliance qui conquiert le temple perdu'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est pas une caractéristique de l\'art de la Renaissance ?', 'Plat/bidimensionnel'));
    this.tab.push(new Answers('À quelle famille célèbre et influente appartenait le célèbre mécène de la Renaissance, le duc Lorenzo ?', 'Médicis'));
    this.tab.push(new Answers('Famille riche à Florence', 'Médicis'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'était pas un pilier de la Renaissance ?', 'Maniérisme'));
    this.tab.push(new Answers('Lequel des mouvements suivants était un mouvement intellectuel de la Renaissance dans lequel les penseurs étudiaient des textes classiques et se concentraient sur le potentiel et les réalisations humaines ?', 'Humanisme'));
    this.tab.push(new Answers('Quelle période de l\'histoire européenne, allant de 1300 à 1600, a vu un regain d\'intérêt pour la culture classique et a conduit à des changements profonds dans l\'art, l\'apprentissage et les visions du monde ?', 'Renaissance'));
    this.tab.push(new Answers('Sans utiliser de buffs, combien de points d\'action un gouverneur peut-il avoir ?', '1000'));
    this.tab.push(new Answers('Quelle unité forte contre l\'infanterie ?', 'Archer'));
    this.tab.push(new Answers('Lequel des commandants suivants excelle à diriger le Calvaire ?', 'Minamoto no Yoshitsune'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'attribue pas de crédits individuels ?', 'Donner des ressources aux alliés.'));
    this.tab.push(new Answers('Quel explorateur portugais a navigué du cap de Bonne-Espérance jusqu\'en Inde ?', 'Vasco de Gama'));
    this.tab.push(new Answers('Pourquoi les grenouilles et autres organismes produisent-ils autant d\'œufs/descendants ?', 'plus il y a de descendants, plus ils ont de chances de survivre'));
    this.tab.push(new Answers('A quoi servent les Flèches de Résistance ?', 'Amélioration de la tour de guet'));
    this.tab.push(new Answers('Les peintres de la Renaissance en Flandre, comme en Italie, avaient tendance à produire quel type d\'œuvres d\'art ?', 'Réaliste'));
    this.tab.push(new Answers('Qu\'est-ce qui a fourni le principal soutien économique à la renaissance ?', 'Riches mécènes'));
    this.tab.push(new Answers('Pourquoi les traits avantageux sont-ils plus susceptibles d\'être transmis à la progéniture ?', 'parce qu\'ils sont plus susceptibles de survivre et de produire...'));
    this.tab.push(new Answers('Après sa fondation au VIe siècle avant notre ère, quelle institution de la République romaine a servi de parlement consultatif ?', 'Le Sénat'));
    this.tab.push(new Answers('Comment appelle-t-on l\'électricité produite par l\'énergie hydraulique à l\'aide de grands barrages dans une rivière ?', 'Énergie hydroélectrique'));
    this.tab.push(new Answers('Le processus de séparation des atomes est connu sous le nom de', 'Fission'));
    this.tab.push(new Answers('Le Père Noël voyage sur un traîneau tiré par quel animal ?', 'Renne'));
    this.tab.push(new Answers('Quelle guerre a opposé les maisons britanniques de Lancaster et d\'York pour le trône d\'Angleterre ?', 'La guerre des roses'));
    this.tab.push(new Answers('Lequel d\'entre eux a été le seul commandant à vaincre Cyrus le Grand au combat ?', 'Tomyris'));
    this.tab.push(new Answers('Lequel des commandants suivants a rejoint une rébellion contre son propre mari ?', 'Constance'));
    this.tab.push(new Answers('Quel commandant est surnommé le Barbare Rugissant ?', 'Lohar'));
    this.tab.push(new Answers('Laquelle des ressources suivantes ne se trouve pas dans votre jean ?', 'Conduire'));
    this.tab.push(new Answers('Quel commandant était associé à Minamoto ?', 'Tomoe Gozen'));
    this.tab.push(new Answers('Lequel des personnages suivants était un général pendant la guerre de Genpei au Japon ?', 'Tomoe Gozen'));
    this.tab.push(new Answers('Dans la mythologie grecque, à qui Paris le prince de troie a-t-il offert une pomme d\'or gravée à la plus belle des déesses ?', 'Aphrodite'));
    this.tab.push(new Answers('Parmi les 12 animaux du zodiaque chinois, lequel vient en premier ?', 'Rat souris'));
    this.tab.push(new Answers('Quelle civilisation a été la première à avoir des toilettes publiques ?', 'Rome antique'));
    this.tab.push(new Answers('Lequel des éléments suivants est un combustible fossile formé d\'organismes marins qui se trouve souvent dans des couches pliées ou inclinées et utilisé pour le chauffage et la cuisine ?', 'Gaz naturel'));
    this.tab.push(new Answers('Du VIIIe au XIe siècle de notre ère, comment les Européens appelaient-ils fréquemment les envahisseurs scandinaves qui ravageaient fréquemment leurs terres ?', 'Vikings'));
    this.tab.push(new Answers('Laquelle des ressources suivantes est une ressource énergétique inépuisable qui repose sur du magma chaud ou des roches sèches chaudes sous terre ?', 'Géo'));
    this.tab.push(new Answers('Lequel des éléments suivants est considéré comme une source d\'énergie ?', 'Pétrole'));
    this.tab.push(new Answers('La Renaissance a été une "Renaissance" de', 'Culture classique'));
    this.tab.push(new Answers('Les avantages de la presse à imprimer de Johannes Gutenberg comprennent tous les éléments suivants, sauf', 'Augmentation du pouvoir de l\'église'));
    this.tab.push(new Answers('', ''));
    this.tab.push(new Answers('', ''));
    this.tab.push(new Answers('Qui a inventé l\'imprimerie ?', 'Jean Gutenberg'));
    this.tab.push(new Answers('Qui a fondé le Royaume des Asturies ?', 'Pélage'));
    this.tab.push(new Answers('Lequel des éléments suivants ne donne PAS d\'EXP aux commandants ?', 'Attaquer d\'autres joueurs'));
    this.tab.push(new Answers('Raphaël est surtout connu pour ?', 'École d\'Athènes'));
    this.tab.push(new Answers('Lequel des éléments suivants est une phase du gouverneur le plus puissant ?', 'Élimination des ennemis'));
    this.tab.push(new Answers('Lequel de ces deux a été créé par Léonard de Vinci ?', 'La Cène, Mona Lisa'));
    this.tab.push(new Answers('Quelle guerre a opposé les Britanniques ?', 'guerre des roses'));
    this.tab.push(new Answers('Quel commandant est surnommé le Gardien de Carthage ?', 'Hannibal Barça'));
    this.tab.push(new Answers('Quelles sont les deux œuvres majeures attribuées à Homère ?', 'L\'Odyssée et l\'Iliade'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est pas un objectif de la mythologie grecque ?', 'Fournir un chemin pour le salut'));
    this.tab.push(new Answers('Quel commandant est surnommé le père de la conquête ?', 'Baïbars'));
    this.tab.push(new Answers('Où la plupart des ouragans commencent-ils ?', 'En pleine mer'));
    this.tab.push(new Answers('Quel commandant est connu comme la Dame des Merciens ?', 'Æthelflæd'));
    this.tab.push(new Answers('Quel monument de Sydney, en Australie, a la forme de voiles ?', 'Opéra de Sydney'));
    this.tab.push(new Answers('L\'économie égyptienne reposait principalement sur quoi ?', 'Agriculture'));
    this.tab.push(new Answers('Quelle planète de notre système solaire tourne le plus vite ?', 'Jupiter'));
    this.tab.push(new Answers('Lequel des commandants suivants a participé à la bataille des falaises rouges ?', 'Cao Cao'));
    this.tab.push(new Answers('Quel est le surnom de Jules César ?', 'Roi sans couronne'));
    this.tab.push(new Answers('Combien de doigts le personnage de dessin animé mickey mouse a-t-il sur chaque main ?', '4'));
    this.tab.push(new Answers('Quel explorateur portugais a été le premier Européen à naviguer jusqu\'à la pointe sud de l\'Afrique ?', 'Bartolomé Dias'));
    this.tab.push(new Answers('Dans quel pays la climatisation a-t-elle été inventée ?', 'Etats-Unis'));
    this.tab.push(new Answers('Les deux capitales de l\'Autriche - Hongrie étaient Budapest et ?', 'Vienne'));
    this.tab.push(new Answers('Dans la mythologie grecque, quelle est la relation entre Zeus et Hermès ?', 'Père et fils'));
    this.tab.push(new Answers('Dans la mythologie grecque, quel héros a demandé la Toison d\'or ?', 'Jason'));
    this.tab.push(new Answers('"La fin justifie les moyens" était une croyance clé de l\'auteur de "Le Prince". Quel était son nom?', 'Machiavel'));
    this.tab.push(new Answers('Où la renaissance a-t-elle commencé ?', 'Italie'));
    this.tab.push(new Answers('Qui a peint la Joconde ?', 'Léonard de Vinci'));
    this.tab.push(new Answers('Les caractères mobiles ont été utilisés pour la première fois dans quel pays ?', 'Chine'));
    this.tab.push(new Answers('Le "nœud de Windsor" a été popularisé par quel roi d\'Angleterre ?', 'Edouard VIII'));
    this.tab.push(new Answers('Quel ancien érudit grec a jeté les bases des futures mathématiques européennes et est l\'auteur des "Éléments" de la géométrie ?', 'Euclide'));
    this.tab.push(new Answers('Qui fut le seul roi d\'Angleterre à être exécuté ?', 'Charles Ier'));
    this.tab.push(new Answers('Par quels quatre mots Oda Nobunaga a-t-elle vécu?', 'Règle avec une force absolue'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est pas une raison pour laquelle la renaissance a commencé en Italie ?', 'La peste noire n\'a pas frappé l\'Italie à cause des Alpes'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est pas un objectif de la mythologie grecque ?', 'Fournir le chemin du salut'));
    this.tab.push(new Answers('Dans des circonstances normales, quelle couche du soleil pouvons-nous voir à l\'œil nu ?', 'Photosphère'));
    this.tab.push(new Answers('Quel commandant est connu sous le nom de Barbarossa ?', 'Frédéric Ier'));
    this.tab.push(new Answers('Lequel des éléments suivants l\'anneau olympique vert représente-t-il ?', 'Océanie'));
    this.tab.push(new Answers('Quel physicien de la Grèce antique a découvert le concept de flottabilité en prenant un bain ?', 'Archimède'));
    this.tab.push(new Answers('Comment obtenir des crédits Alliance Technology ?', 'En faisant un don à l\'Alliance'));
    this.tab.push(new Answers('L\'économie égyptienne était principalement basée sur ?', 'Agriculture'));
    this.tab.push(new Answers('Dans la mythologie grecque, quel était le seul point faible d\'Achille ?', 'Son talon'));
    this.tab.push(new Answers('Les mutations sont un changement de quoi ?', 'ADN'));
    this.tab.push(new Answers('Quel rang honorifique le fondateur de Kentucky Fried Chicken (KFC) a-t-il reçu ?', 'Colonel'));
    this.tab.push(new Answers('Quelle cité-État de la Grèce antique était connue pour son entraînement militaire brutal et sa bravoure ?', 'Sparte'));
    this.tab.push(new Answers('Le Pays de Galles est officiellement devenu une partie du Royaume de Grande-Bretagne sous le règne de quel roi ?', 'Le roi Henri VIII'));
    this.tab.push(new Answers('La reine Victoria d\'Angleterre faisait partie de quelle maison royale ?', 'La maison de Hanovre'));
    this.tab.push(new Answers('Laquelle des sept merveilles du monde a été créée pour guérir le mal du pays de la nouvelle reine de Babylone ?', 'Les jardins suspendus'));
    this.tab.push(new Answers('', ''));
    this.tab.push(new Answers('', ''));
    this.tab.push(new Answers('Lequel des éléments suivants est une source d\'énergie non renouvelable ?', 'Eau'));
    this.tab.push(new Answers('Quel commandant était considéré comme un ennemi de Rome dès son plus jeune âge ?', 'Hannibal Barça'));
    this.tab.push(new Answers('Quel groupe artistique est reconnu comme un « trésor national » du Canada ?', 'Cirque du soleil'));
    this.tab.push(new Answers('Quel empereur romain a été nommé Auguste après avoir mis fin à une guerre civile ?', 'Gaïus Octavius'));
    this.tab.push(new Answers('Dans la mythologie nordique, qui maniait l\'arme Gungnir ?', 'Odin'));
    this.tab.push(new Answers('Les humanistes du Nord comme Erasmus étaient surtout connus pour quoi ?', 'Les cultes'));
    this.tab.push(new Answers('À la Renaissance, pourquoi Florence était-elle importante ?', 'Berceau de la Renaissance'));
    this.tab.push(new Answers('Lequel des énoncés suivants décrit un monothéiste ?', 'Quelqu\'un qui combat 1 dieu.'));
    this.tab.push(new Answers('À qui l\'Inde a-t-elle donné le titre de mahatma ?', 'Mohandas Karamchand Gandhi'));
    this.tab.push(new Answers('Combien de points d\'action un gouverneur peut-il avoir ?', '1000'));
    this.tab.push(new Answers('Lequel des noms suivants désigne une roche sédimentaire formée à partir de matériel végétal en décomposition dans des zones marécageuses ?', 'Charbon'));
    this.tab.push(new Answers('Ashoka le Grand était le roi de quel ancien royaume indien ?', 'Maurya'));
    this.tab.push(new Answers('Sur quel continent l\'espèce humaine est-elle généralement considérée comme originaire ?', 'Afrique'));
    this.tab.push(new Answers('Comment s\'appelle l\'énergie renouvelable issue de la combustion de matières organiques telles que le bois et l\'alcool ?', 'Énergie biomasse'));
    this.tab.push(new Answers('Où le roi Louis XIV de France a-t-il déplacé la cour royale en 1682 ?', 'château de Versailles'));
    this.tab.push(new Answers('Qui était l\'Empereur du Premier Empire français ?', 'Napoléon Bonaparte'));
    this.tab.push(new Answers('Lequel des commandants suivants excelle dans la direction des archers ?', 'Yi Seong-gye'));
    this.tab.push(new Answers('Qui a fondé la dynastie joseon ?', 'Yi Seong-gye'));
    this.tab.push(new Answers('Premier général du shogunat d\'Edo ?', 'Tokugawa Ieyasu'));
    this.tab.push(new Answers('Comment s\'appelle le centre d\'un ouragan ?', 'Œil'));
    this.tab.push(new Answers('Quel homme d\'État éminent a été le premier général du shogunat d\'Edo à la fin de la période des Royaumes combattants ?', 'Tokugawa Ieyasu'));
    this.tab.push(new Answers('Dans l\'Arche d\'Osiris, où êtes-vous censé emmener l\'Arche ?', 'Escorter l\'Arche jusqu\'à un bâtiment non ennemi'));
    this.tab.push(new Answers('Quel groupe a conquis l\'empire byzantin ?', 'Les Ottomans'));
    this.tab.push(new Answers('Où était le point de ralliement de la Première Croisade ?', 'Constantinople'));
    this.tab.push(new Answers('Lequel des termes suivants désigne un matériau précieux d\'origine géologique qui peut être extrait de la terre ?', 'Ressources naturelles'));
    this.tab.push(new Answers('Quelle ville a accueilli les Jeux olympiques d\'été de 2000 ?', 'Sidney'));
    this.tab.push(new Answers('Lequel des éléments suivants est un combustible fossile liquide formé à partir d\'organismes marins qui est brûlé pour obtenir de l\'énergie et utilisé pour fabriquer des plastiques ?', 'Pétrole'));
    this.tab.push(new Answers('Qui a tué Hector et comment meurt Achille ?', 'Achille; Flèche à travers son talon'));
    this.tab.push(new Answers('Créé pour la première fois dans la Grèce antique, à quelle profession s\'applique le serment d\'Hippocrate ?', 'Médecins'));
    this.tab.push(new Answers('Qui a institué le calendrier julien ?', 'Jules César'));
    this.tab.push(new Answers('Qui possédait tout dans les anciens royaumes égyptiens ?', 'pharaon'));
    this.tab.push(new Answers('Quelle partie du corps humain contient le plus d\'eau ?', 'Globes oculaires'));
    this.tab.push(new Answers('Avant de diriger la plus grande rébellion d\'esclaves de la Rome antique, qu\'était Spartacus ?', 'Gladiateur'));
    this.tab.push(new Answers('Quel est le surnom de la championne Keira ?', 'Le caméléon rouge'));
    this.tab.push(new Answers('Ashoka le grand était le roi de quel ancien royaume ?', 'Dynastie Maurya'));
    this.tab.push(new Answers('Quel artiste a conçu la basilique Saint-Pierre au Vatican ?', 'Michel-Ange'));
    this.tab.push(new Answers('Qui a été salué par son compatriote comme le meilleur et le plus honnête représentant démocratique de la Grèce antique ?', 'Périclès'));
    this.tab.push(new Answers('Comment s\'appelle la révolution de 1688 qui établit la monarchie constitutionnelle britannique ?', 'Glorieuse Révolution'));
    this.tab.push(new Answers('Quelle partie du cerveau l\'alcool affectera-t-il ?', 'Cervelet'));
    this.tab.push(new Answers('Qui était l\'empereur du premier Empire français ?', 'Napoléon Bonaparte'));
    this.tab.push(new Answers('Le processus de combinaison des atomes est connu sous quel nom ?', 'La fusion'));
    this.tab.push(new Answers('Laquelle des compétences suivantes ne fait PAS partie des compétences passives de Pélage ?', 'Charge'));
    this.tab.push(new Answers('Quel homme d\'État éminent a été le premier général du shogunat d\'Edo à la fin de la période des États en guerre au Japon ?', 'Tokugawa Ieyasu'));
    this.tab.push(new Answers('Quelle fut la seule civilisation antique à s\'être développée dans une jungle tropicale plutôt que dans un bassin fluvial ?', 'Les Incas'));
    this.tab.push(new Answers('Cité perdue', 'Les Incas'));
    this.tab.push(new Answers('Quel groupe ethnique a fondé la première civilisation de la Mésopotamie ?', 'Les Sumériens'));
    this.tab.push(new Answers('Les vents en forme de cône des tornades sont remarquables pour quoi faire ?', 'Filage'));
    this.tab.push(new Answers('Qui commandait la nouvelle armée modèle fondée par le Parlement pendant la guerre civile anglaise ?', 'Cromwell'));
    this.tab.push(new Answers('Qui est considéré comme le "Père des Jeux Olympiques Modernes" ?', 'Pierre de Coubertin'));
    this.tab.push(new Answers('A quand la déclaration d\'indépendance ?', '1776'));
    this.tab.push(new Answers('Qui était le premier empereur de Rome ?', 'Gaius Octave Auguste'));
    this.tab.push(new Answers('Type d\'unité forte contre l\'infanterie ?', 'Archer'));
    this.tab.push(new Answers('Où le roi Louis XIV de France a-t-il déménagé à la cour royale en 1682 ?', 'château de Versailles'));
    this.tab.push(new Answers('Quelle boisson a été inventée par le pharmacien américain John Pemberton ?', 'Cola'));
    this.tab.push(new Answers('Lequel des commandants suivants excelle dans la collecte de ressources ?', 'Cléopâtre VII'));
    this.tab.push(new Answers('Plus une population a de variations génétiques, plus il est probable qu\'un individu fera quoi ?', 'Survivre'));
    this.tab.push(new Answers('Lequel des commandants suivants excelle dans la direction de l\'infanterie ?', 'Richard I'));
    this.tab.push(new Answers('Lequel des personnages suivants était un ennemi de Richard Cœur de Lion ?', 'Saladin'));
    this.tab.push(new Answers('Dans la mythologie grecque, quel héros a cherché la toison d\'or ?', 'Jason'));
    this.tab.push(new Answers('Quel monument de Sydney, en Australie, a la forme de voiles ?', 'Opéra'));
    this.tab.push(new Answers('D\'où viennent les adaptations ?', 'Les mutations et la recombinaison génétique.'));
    this.tab.push(new Answers('Où Gengis Khan a-t-il commencé à construire son empire mongol ?', 'Asie'));
    this.tab.push(new Answers('Qui était le fondateur de l\'empire mongol ?', 'Gengis Khan'));
    this.tab.push(new Answers('Comment appelle-t-on le phénomène par lequel les organismes mieux adaptés à l\'environnement survivent pour transmettre des traits à leur progéniture ?', 'Sélection naturelle'));
    this.tab.push(new Answers('Lequel des commandants suivants a fait partie de la guerre de Cent Ans ?', 'Jeanne d\'Arc'));
    this.tab.push(new Answers('Quel commandant était surnommé l\'hydromel de la mort ?', 'Sarka'));
    this.tab.push(new Answers('Qu\'est-ce qu\'un monothéiste ?', 'Ne croyez qu\'en un seul dieu.'));
    this.tab.push(new Answers('Quelle découverte a rendu possible le déchiffrement des hiéroglyphes ?', 'Pierre de Rosette.'));
    this.tab.push(new Answers('Les lunettes sont composées de quartz, de sable et de quoi ?', 'Pétrole'));
    this.tab.push(new Answers('Quand Achille refuse de se battre, Patrocle met l\'armure d\'Achille, combat les chevaux de Troie et meurt, par qui Patrocle est-il tué ?', 'Hector'));
    this.tab.push(new Answers('En quelle année Richard et Saladin ont-ils signé une trêve ?', '1192'));
    this.tab.push(new Answers('Les mutations sont importantes car elles entraînent quoi ?', 'Variation génétique nécessaire à l\'évolution d\'une population'));
    this.tab.push(new Answers('Dans l\'Arche d\'Osiris, quelle accélération peut être utilisée ?', 'Accélération de la guérison'));
    this.tab.push(new Answers('Comment Saladin a-t-il changé le Moyen-Orient ?', 'Palestine'));
    this.tab.push(new Answers('Quand la déclaration d\'indépendance a-t-elle été rédigée ?', '1776'));
    this.tab.push(new Answers('L\'empire moghol a porté l\'islam jusqu\'où ?', 'La plupart de l\'Inde'));
    this.tab.push(new Answers('Quel instrument de musique a six cordes ?', 'Guitare'));
    this.tab.push(new Answers('Les quatre plus grandes comédies musicales au monde sont Cats, Les Misérables, Miss Saigon et ?', 'Le fantôme de l\'Opéra'));
    this.tab.push(new Answers('La France et l\'Allemagne faisaient autrefois partie de quel royaume féodal ?', 'France'));
    this.tab.push(new Answers('Dans l\'histoire russe, quel surnom le premier tsar a-t-il donné à leur tyrannie ?', 'Ivan le Terrible'));
    this.tab.push(new Answers('Lequel des éléments suivants est considéré comme une ressource métallique ?', 'Le fer'));
    this.tab.push(new Answers('Quel commandant est connu comme le Conquérant du Chaos ?', 'Cao Cao'));
    this.tab.push(new Answers('Lequel des codes de lois babyloniens était le premier ensemble complet de lois écrites dans l\'histoire enregistrée ?', 'Le Code d\'Hammourabi'));
    this.tab.push(new Answers('Quel Européen a écrit le premier récit de voyage détaillant l\'histoire, la culture et l\'art de la Chine ?', 'Marco Polo'));
    this.tab.push(new Answers('Le format chinois de la comédie à sketches diaphonique trouve son origine à trois endroits : Tianqiao à Pékin, le Quanty Bazaar à Tianjin et où à Nanjing ?', 'Fuzimiao'));
    this.tab.push(new Answers('"L\'Iliade" d\'Homère se concentre sur des événements qui se produisent au cours de quelle guerre ou bataille ?', 'La guerre de Troie'));
    this.tab.push(new Answers('Lequel des éléments suivants ne fait pas partie du drapeau du Mexique ?', 'chameau'));
    this.tab.push(new Answers('Quel commandant était connu sous le nom de Celtic Rose ?', 'Boudica'));
    this.tab.push(new Answers('Quel type de catastrophe naturelle est mesuré à l\'aide de l\'échelle de Richter ?', 'Tremblement de terre'));
    this.tab.push(new Answers('Lequel est reconnu par le Livre Guinness des records comme ayant le plus grand tirage cumulé de toutes les bandes dessinées d\'un seul auteur ?', 'Eichiro Oda / One Piece'));
    this.tab.push(new Answers('Dans la Grèce antique, quel philosophe aimait discuter d\'idées dans une rue qui reçut alors le surnom d\'école péripatéticienne ?', 'Aristote'));
    this.tab.push(new Answers('L\'expérience de Galilée sur la tour penchée de Pise a renversé une théorie de quels scientifiques de la Grèce antique ?', 'Aristote'));
    this.tab.push(new Answers('Quel commandant a montré son génie militaire lors de la bataille de Poitiers au 8ème siècle après JC ?', 'Charles Martel'));
    this.tab.push(new Answers('Quel commandant a montré son génie militaire lors de la bataille de Tours au VIIIe siècle ?', 'Charles Martel'));
    this.tab.push(new Answers('Où les soldats de la Rome antique ont-ils obtenu leurs armes et armures ?', 'Eux-mêmes'));
    this.tab.push(new Answers('Qui a écrit l\'Art de la guerre ?', 'Sun Tzu'));
    this.tab.push(new Answers('Pendant la guerre de Troie, quel guerrier grec a tué Hector ?', 'Achille'));
    this.tab.push(new Answers('Lequel des personnages suivants est le frère aîné de Zeus dans Geek Mythology ?', 'Poséidon'));
    this.tab.push(new Answers('Laquelle des fleurs suivantes est la fleur nationale des Philippines ?', 'Sampaguita'));
    this.tab.push(new Answers('Comment appelle-t-on l\'électricité produite par l\'eau à partir de grands barrages dans une rivière ?', 'Énergie hydroélectrique'));
    this.tab.push(new Answers('De qui l\'autobiographie "Living to Tell the Tale" leur a-t-elle valu le prix Nobel de littérature ?', 'Gabriel Garcia Marquez'));
    this.tab.push(new Answers('Quelle mesure officielle a érigé en crime le fait de donner à manger ou à loger à Martin Luther ?', 'Édit de Worms'));
    this.tab.push(new Answers('Quelle ancienne civilisation a construit la "cité perdue" du Machu Picchu ?', 'Les Incas'));
    this.tab.push(new Answers('Laquelle de ces villes a accueilli les Jeux Olympiques en 1900 ?', 'Paris'));
    this.tab.push(new Answers('Le Taj Mahal a été construit au cours de quelle dynastie indienne ?', 'La dynastie moghole'));
    this.tab.push(new Answers('Quel empereur a publié la Proclamation de Milan ?', 'Constantin Ier'));
    this.tab.push(new Answers('Lequel des succès suivants doit être accompli avant le succès "Flocon de neige spécial" ?', 'Frappe à longue portée'));
    this.tab.push(new Answers('En quoi le commandant Lancelot est-il doué ?', 'Unités de cavalerie de tête'));
    this.tab.push(new Answers('En quoi le commandant Baybars est-il doué ?', 'Unités de cavalerie de tête'));
    this.tab.push(new Answers('En quoi le commandant Hermann est-il doué ?', 'Archers de tête'));
    this.tab.push(new Answers('Lorsque la mairie d\'un gouverneur atteint le niveau 25, combien de fermes peut-il construire ?', '4'));
    this.tab.push(new Answers('En quoi le commandant Keira est-il doué ?', 'Archers de tête'));
    this.tab.push(new Answers('En quoi le commandant Osman I est-il doué ?', 'Attaquer des villes'));
    this.tab.push(new Answers('Quel buff peut être obtenu en occupant un sanctuaire du courage ?', 'Augmente l\'EXP gagnée par les commandants'));
    this.tab.push(new Answers('En quoi le commandant Hannibal Barca est-il bon?', 'Attaquer des villes'));
    this.tab.push(new Answers('Qui a eu l\'idée du cheval de Troie ?', 'Ulysse'));
    this.tab.push(new Answers('Qui a gagné la guerre de Troie ?', 'Les Grecs'));
    this.tab.push(new Answers('ancienne partie empire maintenant sur quel pays asiatique atterrit', 'L\'Iran'));
    this.tab.push(new Answers('En quoi le commandant Eulji Mundeok est-il doué ?', 'Unités d\'infanterie de tête'));
    this.tab.push(new Answers('Qu\'est-ce qui cause les éclipses lunaires ?', 'La terre se déplace directement entre le soleil et la lune'));
    this.tab.push(new Answers('Au cours de la seconde guerre punique, dans quelle bataille un Hannibal largement en infériorité numérique a-t-il vaincu une armée romaine ?', 'La bataille de Cannes'));
    this.tab.push(new Answers('"La fin justifie les moyens" était une croyance clé de l\'auteur de "Le Prince". Quel était son nom?', 'Machiavel'));
    this.tab.push(new Answers('Un « jour » sur la planète Vénus est approximativement égal à combien de jours terrestres ?', '243 jours'));
    this.tab.push(new Answers('Laquelle des nations suivantes est la plus proche du pôle Nord ?', 'Finlande'));
    this.tab.push(new Answers('Parmi les suivants, lequel n\'est PAS l\'un des principaux gaz à effet de serre dans l\'atmosphère terrestre ?', 'Azote'));
    this.tab.push(new Answers('Quelle était une autre utilisation du gin, en plus d\'être une boisson populaire, au 18ème siècle ?', 'Médecine'));
    this.tab.push(new Answers('Lors de la capture et de la remise à l\'eau de poissons d\'eau profonde, pourquoi est-il important de percer leur vessie natatoire ?', 'Pour les empêcher de mourir de vessie natatoire distendue'));
    this.tab.push(new Answers('Lequel des facteurs suivants permet de superposer certaines boissons mélangées ?', 'Densité'));
    this.tab.push(new Answers('Parmi les races de chats suivantes, laquelle est connue pour être dépourvue de poils ?', 'Sphynx'));
    this.tab.push(new Answers('Quand est la Journée internationale des forêts?', '44641'));
    this.tab.push(new Answers('Quand est la journée mondiale sans tabac ?', '44712'));
    this.tab.push(new Answers('Quand les dinosaures ont-ils existé pour la première fois ?', 'Trias'));
    this.tab.push(new Answers('Quelle nation n\'a PAS participé à la bataille de Waterloo ?', 'Italie'));
    this.tab.push(new Answers('En quoi le commandant Sun Tzu est-il doué ?', 'Mener les garnisons de la ville.'));
    this.tab.push(new Answers('L\'air est souvent plus frais après un orage car il a été enrichi avec quel gaz ?', 'Ozone'));
    this.tab.push(new Answers('Le grand Asoka, qui était le roi de l\'ancien royaume indien', 'Maurya'));
    this.tab.push(new Answers('Qui a eu l\'idée du cheval de Troie ? Qui a gagné la guerre de Troie ?', 'Ulysse; Les Grecs'));
    this.tab.push(new Answers('Parmi les compétences suivantes, laquelle ne fait pas partie des compétences d\'Hermann ?', 'Irrésistible'));
    this.tab.push(new Answers('Keira a une fois défié les attentes du monde à son sujet dans une bataille glorieuse. Où cette bataille a-t-elle eu lieu ?', 'Canyon du coucher du soleil'));
    this.tab.push(new Answers('Le Temple du Ciel chinois a été construit sous le règne de quel empereur ?', 'L\'Empereur Yongle (Zhu Di)'));
    this.tab.push(new Answers('Lequel des éléments suivants ne fait PAS partie des compétences de Keira ?', 'Sang indiscipliné'));
    this.tab.push(new Answers('Le titre de royaume "Reine" augmente lequel des éléments suivants ?', 'Vitesse de collecte'));
    this.tab.push(new Answers('Combien d\'os un humain adulte possède-t-il ?', '206'));
    this.tab.push(new Answers('Qui a financé les voyages de Christophe Colomb ?', 'Espagne'));
    this.tab.push(new Answers('Qui fut le premier des enfants d\'Henri VIII à gouverner l\'Angleterre ?', 'Edouard VI'));
    this.tab.push(new Answers('Henri Ier monta sur le trône d\'Angleterre en l\'an 1100, après quel parent mourut ?', 'Son frère'));
    this.tab.push(new Answers('Qu\'est-ce qui cause l\'odeur caractéristique dans l\'air après la pluie ?', 'L\'influence des actinomycètes'));
    this.tab.push(new Answers('Parmi les nations suivantes, laquelle a la plus petite superficie ?', 'Cité du Vatican'));
    this.tab.push(new Answers('Quelle est la partie la plus dure du corps humain ?', 'Émail dentaire'));
    this.tab.push(new Answers('Dans la plupart des cas, quel type de moustiques boit du sang animal ?', 'Moustiques femelles'));
    this.tab.push(new Answers('Quel personnage historique est enterré dans le Temple des Inscriptions de Palenque ?', 'Pakal le Grand'));
    this.tab.push(new Answers('Où le roi Jean d\'Angleterre a-t-il accepté la Magna Carta en 1215 ?', 'Runnymede'));
    this.tab.push(new Answers('Lequel des énoncés suivants est une description précise du climat méditerranéen ?', 'Des étés chauds et secs et des hivers frais et humides.'));
    this.tab.push(new Answers('Laquelle des compétences suivantes ne fait PAS partie des compétences d\'Osman I ?', 'Tactiques obliques'));
    this.tab.push(new Answers('Laquelle des compétences suivantes ne fait PAS partie des compétences de Belisarius ?', 'Force tonitruante'));
    this.tab.push(new Answers('Parmi les descriptions de titre de royaume suivantes, lesquelles sont INCORRECTES ?', 'Le Premier ministre a augmenté l\'attaque des troupes.'));
    this.tab.push(new Answers('Dans la page Commander View, quel buff les commandants agissant en tant que "drillmaster" obtiennent-ils ?', '+1 % d\'attaque de troupes'));
    this.tab.push(new Answers('Dans la page Commander View, quel buff les commandants agissant en tant que "Ranger" obtiennent-ils ?', '+5 % de gain d\'XP et de dégâts contre les barbares (aucune de ces réponses)'));
    this.tab.push(new Answers('Dans la page d\'affichage du commandant, quel buff les commandants agissant en tant qu\'"agent des impôts" obtiennent-ils ?', '+5 % de vitesse de collecte'));
    this.tab.push(new Answers('Dans la page d\'affichage du commandant, quel buff les commandants agissant en tant que "Garde de fer" obtiennent-ils ?', '+1 % de santé des troupes'));
    this.tab.push(new Answers('Dans la page d\'affichage du commandant, quel buff les commandants agissant en tant que "capitaine de ravitaillement" obtiennent-ils ?', '+5 % de vitesse de rassemblement et de charge de troupes'));
    this.tab.push(new Answers('Dans la page Commander View, quel buff les commandants agissant en tant que "Charge Captain" obtiennent-ils ?', '+1 % d\'attaque de ralliement et de vitesse de marche des troupes de ralliement'));
    this.tab.push(new Answers('Dans la page Commander View, quel buff les commandants agissant en tant que "King Head" obtiennent-ils ?', '+1 % de défense et de santé des troupes'));
    this.tab.push(new Answers('Où est né le commandant Lohar ?', 'Dans une tribu barbare éloignée.'));
    this.tab.push(new Answers('Parmi les commandants ci-dessous, lequel est le mieux adapté pour diriger des troupes contre des ennemis d\'infanterie ?', 'Hermann'));
    this.tab.push(new Answers('Lequel des suivants a été salué par ses compatriotes comme le meilleur et le plus honnête représentant démocratique de la Grèce antique ?', 'Périclès'));
    this.tab.push(new Answers('Parmi les commandants ci-dessous, lequel est le mieux adapté pour diriger des troupes CONTRE des archers ennemis ?', 'Cao Cao'));
    this.tab.push(new Answers('Parmi les commandants ci-dessous, lequel est le mieux adapté pour diriger des troupes CONTRE des ennemis de cavalerie ?', 'Sun Tzu'));
    this.tab.push(new Answers('Parmi les commandants ci-dessous, lequel est le mieux adapté pour diriger des troupes lors de la collecte de ressources ?', 'Seondeok'));
    this.tab.push(new Answers('Dans quel pays se trouve le mystérieux Stonehenge ?', 'Royaume-Uni'));
    this.tab.push(new Answers('Sous la dynastie Han en Chine, qui a ouvert la route de la soie sur ordre de l\'empereur Wu ?', 'Zhang Qian'));
    this.tab.push(new Answers('Pourquoi le scorbut était-il autrefois un problème courant pour les marins ?', 'Un manque de fruits et légumes frais sur les longs voyages'));
    this.tab.push(new Answers('Pourquoi boire du café rend-il les gens plus éveillés ?', 'Il contient de la caféine'));
    this.tab.push(new Answers('Laquelle des maladies suivantes peut être causée par un manque de vitamine D ?', 'Rachitisme'));
    this.tab.push(new Answers('Lequel des commandants suivants excelle à diriger la cavalerie ?', 'Minamoto no Yoshitsune'));
    this.tab.push(new Answers('En quelle année Richard Cœur de Lion et Saladin ont-ils signé une trêve ?', '1192'));
    this.tab.push(new Answers('Qu\'est-ce qui n\'est PAS une compétence royale ?', 'Le soulagement'));
    this.tab.push(new Answers('Quelle contribution exceptionnelle à la science a valu au biologiste Karl Landsteiner le prix Nobel ?', 'A la découverte des groupes sanguins humains'));
    this.tab.push(new Answers('Dans la plupart des cas, quel type de lion a une crinière ?', 'Mâle adulte'));
    this.tab.push(new Answers('Quel est l\'emplacement du mystérieux Stoneage ?', 'Allemagne'));
    this.tab.push(new Answers('Quelle était la relation entre les célèbres généraux Tolui et Gengis Khan ?', 'Père et fils'));
    this.tab.push(new Answers('Laquelle des vitamines suivantes est la plus utile pour maintenir une bonne vision ?', 'Vitamine A'));
    this.tab.push(new Answers('Parmi les descriptions de titre de royaume suivantes, lesquelles sont INCORRECTES ?', 'Les ducs ont augmenté l\'attaque des troupes'));
    this.tab.push(new Answers('Quelle est la fonction principale des globules blancs dans le corps humain ?', 'Combattre les infections et les maladies'));
    this.tab.push(new Answers('Laquelle de ces villes du Brésil a accueilli les Jeux olympiques ?', 'Rio de Janeiro'));
    this.tab.push(new Answers('En quelle année Alexander Fleming a-t-il découvert la pénicilline ?', '1928'));
    this.tab.push(new Answers('Lequel des pays suivants est entièrement situé dans l\'hémisphère nord ?', 'Aucune de ces réponses n\'est correcte'));
    this.tab.push(new Answers('Lequel de ces pays traverse le premier méridien ?', 'Mali'));
    this.tab.push(new Answers('Lequel des énoncés suivants décrit avec précision le cercle polaire arctique ?', 'Le jour polaire et la nuit polaire sont des phénomènes qui s\'y produisent'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est PAS l\'une des compétences de Matilda of Flanders ?', 'Sang celtique'));
    this.tab.push(new Answers('Laquelle des compétences suivantes ne fait PAS partie des compétences de Mulan ?', 'Armée indomptable'));
    this.tab.push(new Answers('Quel pays a été le premier à inventer le parfum ?', 'Chypre'));
    this.tab.push(new Answers('Quelle est la principale cause de la formation de l\'Himalaya ?', 'Collision entre plaques'));
    this.tab.push(new Answers('Dans la mythologie grecque, comment appelle-t-on la déesse Eos ?', 'Déesse de l\'aube'));
    this.tab.push(new Answers('Quel dieu est Taranis dans la mythologie celtique ?', 'Dieu du tonnerre'));
    this.tab.push(new Answers('Pendant la période des Royaumes combattants de la Chine, quel État a vaincu les six autres et construit l\'empire chinois unifié ?', 'Qin'));
    this.tab.push(new Answers('Quelle est la principale cause des reliefs karstiques ?', 'La dissolution des roches solubles'));
    this.tab.push(new Answers('La Bastille, une prison autrefois située au centre de Paris, en France, servait à l\'origine à quoi ?', 'Forteresse défensive'));
    this.tab.push(new Answers('Lequel des médecins suivants a été le premier à décrire complètement et en détail la circulation systémique et la fonction du cœur ?', 'Guillaume Harvey'));
    this.tab.push(new Answers('Dans quel pays est né Marco Polo, célèbre explorateur et marchand ?', 'République de Venise'));
    this.tab.push(new Answers('Où a été trouvée l\'Armée de terre cuite du patrimoine mondial ?', 'Dans un mausolée royal'));
    this.tab.push(new Answers('servile', 'Afrique'));
    this.tab.push(new Answers('cause du relief karstique', 'dissolution des roches solubles'));
    this.tab.push(new Answers('Lequel de ces animaux ne pond PAS d\'œufs ?', 'Chauve souris'));
    this.tab.push(new Answers('À part "Nombre de fois où vous pouvez être aidé" et "Puissance", lesquels des paramètres Alliance Center suivants peuvent également être mis à niveau ?', 'Capacité des troupes de renfort'));
    this.tab.push(new Answers('En dehors du "Nombre de Scouts" et de la "Puissance", lesquels des paramètres suivants du Scout Camp peuvent également être mis à jour ?', 'Scout March Vitesse et portée d\'exploration'));
    this.tab.push(new Answers('Que fait la compétence d\'alliance "cadeau de la nature" ?', 'Invoquer un point de ressources dans une zone sélectionnée (ne peut pas être utilisé dans le royaume perdu)'));
    this.tab.push(new Answers('Lequel de ces deux a été créé par Léonard de Vinci ?', 'La Cène, Mona Lisa'));
    this.tab.push(new Answers('Quelle est la cause première du mal de l\'altitude ?', 'Exposition rapide à de faibles quantités d\'oxygène à haute altitude'));
    this.tab.push(new Answers('Lequel des bâtiments suivants ne peut pas être amélioré ?', 'Poste de courrier'));
    this.tab.push(new Answers('À quoi sert la compétence d\'alliance "entièrement chargée" ?', 'Augmente la vitesse de collecte des membres de l\'alliance pour un type de ressource.'));
    this.tab.push(new Answers('Quelle technologie précède Swordsman ?', 'Travail du fer'));
    this.tab.push(new Answers('Lequel des énoncés suivants décrit le mieux un poisson-clown ?', 'Poissons marins tropicaux'));
    this.tab.push(new Answers('Quelle technologie vient avant Pavise ?', 'Flèches Bodkin'));
    this.tab.push(new Answers('Quelle technologie vient juste avant la cavalerie lourde ?', 'Armure d\'écailles'));
    this.tab.push(new Answers('Dans l\'Égypte ancienne, lequel des éléments suivants n\'était PAS un privilège d\'être un « scribe » ?', 'Exonération des frais médicaux en cas de maladie'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'était pas un avantage d\'être un scribe de l\'Égypte ancienne ?', 'Hors indemnité médicale d\'avance maladie'));
    this.tab.push(new Answers('Comment la Bible de Gutenberg a-t-elle été mise en production de masse ?', 'Presse à imprimer à caractères mobiles'));
    this.tab.push(new Answers('En quelle année le Code Napoléon a-t-il été créé ?', '1804'));
    this.tab.push(new Answers('Quel scientifique néerlandais est connu comme "le père de la microbiologie" ?', 'Antoine van Leeuwenhoek'));
    this.tab.push(new Answers('Dans quel pays est né le célèbre stratège révolutionnaire et militaire Simón Bolívar ?', 'Venezuela'));
    this.tab.push(new Answers('Où est la capitale de l\'Écosse ?', 'Edinbourg'));
    this.tab.push(new Answers('Depuis sa fondation en 1863, combien de fois le Comité international de la Croix-Rouge a-t-il remporté le prix Nobel de la paix ?', '3'));
    this.tab.push(new Answers('Le roman Romance of the Three Kingdoms commence vers la fin de quelle dynastie chinoise ?', 'Han'));
    this.tab.push(new Answers('Dans quel théâtre la Symphonie n°5 en ut mineur de Beethoven a-t-elle été créée en 1808 ?', 'Le Théâtre et der Wien'));
    this.tab.push(new Answers('En code Morse, quelle est la longueur en points entre deux mots ?', 'sept'));
    this.tab.push(new Answers('Qui était le dernier empereur du Saint Empire romain germanique ?', 'François II'));
    this.tab.push(new Answers('Après qu\'un Venus Flytrap attrape un insecte, comment digère-t-il et absorbe-t-il la proie ?', 'Les volets internes des feuilles sécrètent un liquide digestif'));
    this.tab.push(new Answers('Parmi les éléments suivants, lequel est le plus susceptible d\'avoir directement conduit à l\'âge du bronze ?', 'Le bronze est plus dur et plus durable que les autres métaux disponibles à l\'époque.'));
    this.tab.push(new Answers('Lequel des éléments suivants est un bâtiment économique ?', 'Centre de l\'Alliance'));
    this.tab.push(new Answers('Lequel des éléments suivants attribue des points d\'activité quotidienne ?', 'Vaincre les troupes barbares sur la carte'));
    this.tab.push(new Answers('Parmi les villes suivantes, laquelle a été la première à disposer d\'un système de transport en commun rapide souterrain ?', 'Londres'));
    this.tab.push(new Answers('Pourquoi l\'infirmière britannique Florence Nightingale était-elle connue sous le nom de "La Dame à la lampe" ?', 'Elle inspecterait les patients la nuit'));
    this.tab.push(new Answers('Qui fut le premier roi d\'Italie après son unification en 1861 ?', 'Victor-Emmanuel II'));
    this.tab.push(new Answers('Quel titre détenait Pierre de Coubertin, fondateur du Comité International Olympique ?', 'Baron'));
    this.tab.push(new Answers('En quelle année a eu lieu le premier championnat de tennis de Wimbledon ?', '1877'));
    this.tab.push(new Answers('Parmi les suivants, lequel est le premier parc national au monde ?', 'le parc national de Yellowstone'));
    this.tab.push(new Answers('Dans quel pays le groupe Carlsberg, un brasseur de premier plan, a-t-il été fondé en 1847 ?', 'Danemark'));
    this.tab.push(new Answers('Que fait la compétence d\'alliance "Skillful Craftsman" lorsqu\'elle est utilisée ?', 'Augmente considérablement la vitesse de construction du drapeau d\'alliance.'));
    this.tab.push(new Answers('Combien de coffres de récompense sont attribués pour avoir atteint 60 points d\'activité quotidiens ?', '3'));
    this.tab.push(new Answers('Laquelle des structures suivantes est un bâtiment militaire ?', 'Camp scout'));
    this.tab.push(new Answers('Quelles sont les dimensions du brouillard dissipé par un élément de la carte du royaume ?', '10x10'));
    this.tab.push(new Answers('Qu\'est-ce qui a causé la mort de Périclès ?', 'Une peste.'));
    this.tab.push(new Answers('Pourquoi les cônes en forme de vent des tornades sont-ils célèbres ?', 'Filage'));
    this.tab.push(new Answers('Combien de temps dure l\'item Builder Recruitment ?', '2 jours'));
    this.tab.push(new Answers('À partir de quel niveau VIP débloquez-vous définitivement une deuxième file d\'attente de bâtiment ?', 'Niveau 6'));
    this.tab.push(new Answers('Combien de fois pouvez-vous recevoir de l\'aide d\'alliance si votre centre d\'alliance est au niveau 25 ?', '30'));
    this.tab.push(new Answers('Au cours de quel règne d\'empereur le Colisée romain a-t-il été achevé ?', 'Tite'));
    this.tab.push(new Answers('Frère aîné de Zeus', 'Poséidon'));
    this.tab.push(new Answers('Quelle est la capacité de troupes ralliées par défaut lorsque votre château est au niveau 25 ?', '2 millions'));
    this.tab.push(new Answers('En combien de khanats ou d\'empires séparés l\'empire mongol s\'était-il fracturé au moment de la mort de Kublai en 1294 ?', '4'));
    this.tab.push(new Answers('Qui a initié la première Marche du Sel ?', 'Mahatma Ghandi'));
    this.tab.push(new Answers('Tenue en 1929, combien de temps a duré la première cérémonie des Oscars ?', '15 minutes'));
    this.tab.push(new Answers('Le zeppelin a été inventé par des ingénieurs de quel pays ?', 'Allemagne'));
    this.tab.push(new Answers('Lors de son tragique voyage inaugural, quelle était la destination prévue du Titanic ?', 'New York'));
    this.tab.push(new Answers('Que faisait Theodorus van Gogh, le frère cadet du célèbre peintre hollandais Vincent Van Gogh, dans la vie ?', 'Marchand d\'art'));
    this.tab.push(new Answers('En quelle année Einstein a-t-il publié ses quatre Annus Mirabilis ("Miracle Papers") ?', '1905'));
    this.tab.push(new Answers('Quels sont les deux océans reliés par le canal de Panama ?', 'Les océans Pacifique et Atlantique'));
    this.tab.push(new Answers('Pour quelle maladie Edward Jenner, connu comme le père de l\'immunologie, a-t-il développé un vaccin ?', 'Variole'));
    this.tab.push(new Answers('Lequel des éléments suivants est un bâtiment décoratif ?', 'Tambour de pierre'));
    this.tab.push(new Answers('Quel était le surnom de Bélisaire ?', 'Le dernier des romains'));
    this.tab.push(new Answers('Combien de points VIP pouvez-vous acheter avec 200 gemmes ?', '200'));
    this.tab.push(new Answers('Qu\'est-ce qui a causé la mort de l\'éminent homme d\'État et stratège militaire Périclès ?', 'Une peste'));
    this.tab.push(new Answers('Lequel des éléments suivants est le plus susceptible d\'avoir directement conduit à l\'âge du bronze ?', 'Le bronze est plus dur et plus durable que les autres métaux disponibles à l\'époque'));
    this.tab.push(new Answers('Quel Pharaon a ordonné la construction des temples d\'Abou Simbel ?', 'Ramsès II'));
    this.tab.push(new Answers('Lequel des événements suivants ne s\'est PAS produit pendant les guerres gréco-perses ?', 'La bataille d\'Azincourt'));
    this.tab.push(new Answers('Dans quelle écriture le Code d\'Hammourabi a-t-il été gravé sur la pierre ?', 'Cunéiforme'));
    this.tab.push(new Answers('Selon l\'histoire de la louve dans la mythologie romaine, qu\'est-il advenu des jumeaux qu\'elle a nourris, Romulus et Remus ?', 'Romulus est devenu le fondateur et le premier roi de Rome'));
    this.tab.push(new Answers('Dans quelle ville moderne le Shakespeare\'s Globe Theatre a-t-il été construit ?', 'Londres'));
    this.tab.push(new Answers('De combien un objet Enhanced Attack (Advanced) augmentera-t-il votre attaque ?', 'dix%'));
    this.tab.push(new Answers('De quoi se cachaient les hommes et les femmes à la périphérie de Florence dans le recueil de romans "Le Décaméron" ?', 'La peste noire'));
    this.tab.push(new Answers('Quel était le célèbre discours d\'Otto von Bismarck concernant en 1862 ?', 'Sang et fer'));
    this.tab.push(new Answers('Pourquoi la mer Morte a-t-elle reçu ce nom ?', 'L\'eau hautement salée empêche les plantes et les animaux de prospérer à proximité.'));
    this.tab.push(new Answers('Qui était le seul président américain à avoir servi plus de 2 mandats ?', 'Franklin D. Roosevelt'));
    this.tab.push(new Answers('À quoi le mot "Formua" dans "Formula 1 Racing" fait-il référence ?', 'Les règles que les voitures participantes doivent suivre'));
    this.tab.push(new Answers('Quel est le plus ancien festival de cinéma au monde ?', 'Festival du film de Venise'));
    this.tab.push(new Answers('Édouard VIII est devenu roi d\'Angleterre en janvier 1936. Plus tard dans la même année, en quel mois a-t-il abandonné le trône ?', 'Décembre'));
    this.tab.push(new Answers('Qui a initié la première Marche du Sel ?', 'Mahatma Ghandi'));
    this.tab.push(new Answers('Qui a été le premier astronaute à entrer dans l\'espace ?', 'Youri Gagarine'));
    this.tab.push(new Answers('Parmi les personnes suivantes, lesquelles sont nées la même année que le chanteur Luciano Pavarotti ?', 'Elvis Presley'));
    this.tab.push(new Answers('Dans quelle ville britannique les Beatles ont-ils été fondés en 1960 ?', 'Liverpool'));
    this.tab.push(new Answers('Édouard VIII est devenu roi d\'Angleterre en janvier 1936. Plus tard dans la même année, en quel mois a-t-il abandonné le trône ?', 'Décembre'));
    this.tab.push(new Answers('Dans quelle écriture le Code d\'Hammourabi a-t-il été gravé sur la pierre ?', 'Cunéiforme'));
    this.tab.push(new Answers('Quel commandant a montré son génie militaire lors de la bataille de Tours au VIIIe siècle ?', 'Charles Martel'));
    this.tab.push(new Answers('Selon l\'histoire de la louve dans la mythologie romaine, qu\'est-il advenu des jumeaux qu\'elle a nourris, Romulus et Remus ?', 'Romulus est devenu le fondateur et le premier roi de Rome'));
    this.tab.push(new Answers('De quoi se cachaient les hommes et les femmes à la périphérie de Florence dans la nouvelle collection "Le Décaméron" ?', 'La peste noire'));
    this.tab.push(new Answers('Lequel des discours suivants a été prononcé par le Premier ministre prussien Otto von Bismarck en septembre 1862 ?', 'Sang et fer'));
    this.tab.push(new Answers('Quelle civilisation accorde un bonus d\'attaque de 5 % aux unités de cavalerie ?', 'Allemagne'));
    this.tab.push(new Answers('Dans quelle mesure un objet Enhanced Gathering augmentera-t-il votre vitesse de collecte ?', '0,5'));
    this.tab.push(new Answers('Le roman Romance of the Three Kingdoms commence vers la fin de laquelle la dynastie chinoise', 'Han'));
    this.tab.push(new Answers('Qui était le fondateur du Edo Bakufu du Japon ?', 'Tokugawa Ieyasu'));
    this.tab.push(new Answers('Quelle est la durée de l\'élément Builder Recruitment ?', '2 jours'));
    this.tab.push(new Answers('Dans quelle ville moderne le Shakespeare\'s Globe Theatre a-t-il été construit ?', 'Londres'));
    this.tab.push(new Answers('Laquelle des histoires suivantes ne fait pas partie du conte de fées de Grimm ?', 'La petite Sirène'));
    this.tab.push(new Answers('Qui a été la première femme à remporter un prix Nobel ?', 'Marie Curie'));
    this.tab.push(new Answers('Quelle dynastie chinoise Jiang Ziya a-t-il aidé à établir ?', 'La dynastie Zhou'));
    this.tab.push(new Answers('Quelles sont les deux villes reliées par le pont Dom Luis au Portugal ?', 'Porta, Vila Nova de Gaïa'));
    this.tab.push(new Answers('Quel était le but initial de la Grande Pyramide de Gizeh ?', 'La tombe du pharaon Khéops'));
    this.tab.push(new Answers('Et si les buffs suivants pouvaient prendre effet pendant les batailles de Sunset Canyon ?', 'Buffs de l\'équipement'));
    this.tab.push(new Answers('Quel était le nom royal du dernier empereur de la dynastie Qing de Chine ?', 'Xuantong'));
    this.tab.push(new Answers('Laquelle des œuvres suivantes est basée sur la bataille du col de Roncevaux, menée par Charlemagne et ses chevaliers ?', 'La chanson de Roland'));
    this.tab.push(new Answers('Quelle est la seule comète à courte période connue qui soit régulièrement visible à l\'œil nu depuis la Terre ?', 'La comète de Halley'));
    this.tab.push(new Answers('Dans la mythologie nordique, à qui appartient le marteau Mjolnir ?', 'Thor'));
    this.tab.push(new Answers('Quel philosophe a écrit "Utopie" ?', 'Platon'));
    this.tab.push(new Answers('L\'intolérance au lactose est causée par une pénurie de quoi?', 'Lactase'));
    this.tab.push(new Answers('Pourquoi la proue et la poupe des chaloupes vikings étaient-elles conçues pour être symétriques ?', 'Pour inverser rapidement la direction sans faire demi-tour'));
    this.tab.push(new Answers('En 1998, la 16e Coupe du Monde de la FIFA s\'est déroulée dans quel pays ?', 'France'));
    this.tab.push(new Answers('Dans quel pays se trouve Catalhoyuk (Çatalhöyük) ?', 'Turquie'));
    this.tab.push(new Answers('Dans l\'Arche d\'Osiris, combien de téléportations la première alliance à occuper un obélisque gagne-t-elle ?', '8'));
    this.tab.push(new Answers('La fête nationale française est le 14 juillet pour coïncider avec quel événement historique ?', 'Prise de la Bastille'));
    this.tab.push(new Answers('Laquelle des ressources suivantes n\'est pas une ressource naturelle ?', 'Vêtements'));
    this.tab.push(new Answers('Le Throwing Axman est l\'unité spéciale de quelle civilisation ?', 'France'));
    this.tab.push(new Answers('Le jour de l\'Elbe a été la rencontre de quelles deux armées pendant la Seconde Guerre mondiale ?', 'États-Unis, URSS'));
    this.tab.push(new Answers('Lequel des textes suivants a été écrit par Mary Shelley ?', 'Frankenstein'));
    this.tab.push(new Answers('Qui ont été les premiers alpinistes enregistrés à atteindre le sommet du mont Everest ?', 'Tenzing Norgay et Edmund Hilary'));
    this.tab.push(new Answers('Quelle est la capacité de transport par défaut si votre poste de traite est au niveau 25 ?', '5 millions'));
    this.tab.push(new Answers('Le brocoli est riche en quelle vitamine ?', 'Vitamine C'));
    this.tab.push(new Answers('Quelle école de pensée a été fondée par le philosophe chinois Lao Tzu ?', 'taoïsme'));
    this.tab.push(new Answers('Sur quel continent le serval a-t-il vécu pour la première fois ?', 'Afrique'));
    this.tab.push(new Answers('Qui a prononcé le célèbre discours "I Have a Dream" ?', 'Martin Luther King jr.'));
    this.tab.push(new Answers('Dans RoK, le Throwing Axeman est l\'unité spéciale de quelle civilisation', 'France'));
    this.tab.push(new Answers('Lequel des textes suivants a été écrit par Mary Shelley ?', 'Frankenstein'));
    this.tab.push(new Answers('Emblème national de l\'Irlande', 'Harpe'));
    this.tab.push(new Answers('A quelle saison les nuits sont-elles relativement courtes et les jours relativement longs ?', 'Été'));
    this.tab.push(new Answers('Laquelle des civilisations suivantes augmente les dégâts des compétences de commandant actif de 5 % ?', 'Ottomans'));
    this.tab.push(new Answers('Dans quelle galerie se trouve actuellement la Joconde ?', 'Le Louvre'));
    this.tab.push(new Answers('Qui est l\'auteur du roman "No Longer Human" ?', 'Osamu Dazaï'));
    this.tab.push(new Answers('Qui est le « dieu de l\'amour » dans la mythologie nordique ?', 'Freyja'));
    this.tab.push(new Answers('Le "rêve américain" est enraciné dans lequel de ces documents ?', 'La déclaration d\'indépendance'));
    this.tab.push(new Answers('La "Marche de l\'Indépendance" est l\'hymne national de quel pays ?', 'Turquie'));
    this.tab.push(new Answers('De quelle école de peinture Georges Seurat serait-il le représentant ?', 'Pointillisme'));
    this.tab.push(new Answers('Dans quel palais anglais la "Chambre des Étoiles" a-t-elle siégé ?', 'Palais de Westminster'));
    this.tab.push(new Answers('Édouard VIII est devenu roi d\'Angleterre en janvier 1936. Plus tard dans la même année, en quel mois a-t-il abandonné le trône ?', 'Décembre'));
    this.tab.push(new Answers('Laquelle de ces compétences actives appartient à Charles Martel ?', 'Bouclier immortel'));
    this.tab.push(new Answers('En quelle année la première édition du "Journal d\'Anne Frank" a-t-elle été publiée ?', '1947'));
    this.tab.push(new Answers('Dans quel pays le microscope a-t-il été inventé ?', 'Les Pays-Bas'));
    this.tab.push(new Answers('Le dernier livre de Darwin traitait principalement de l\'influence de quelle espèce sur le sol ?', 'Vers de terre'));
    this.tab.push(new Answers('Combien de médailles d\'or olympiques l\'Afro-américain Jesse Owens a-t-il remportées en 1936 ?', '4'));
    this.tab.push(new Answers('Dans la mythologie nordique, quelle variété d\'arbres était l\'arbre du monde ?', 'Cendre'));
    this.tab.push(new Answers('Le phénomène « El Nino » porte le nom de laquelle de ces fêtes ?', 'Noël'));
    this.tab.push(new Answers('"Tongwancheng" était la capitale de quel groupe ethnique de la Chine ancienne ?', 'Les Xiongnu'));
    this.tab.push(new Answers('Charles Macintosh a fabriqué une toute première version d\'un imperméable à partir de quel matériau ?', 'Caoutchouc'));
    this.tab.push(new Answers('Une diminution de laquelle des mesures suivantes pourrait indiquer une proximité croissante avec un état de vide ?', 'Pression de l\'air'));
    this.tab.push(new Answers('Quels sont les deux pays qui constituaient ensemble l\'"Union ibérique" ?', 'Portugal et Espagne'));
    this.tab.push(new Answers('Lequel de ces navigateurs fut le premier Européen à arriver au Brésil ?', 'Pedro Alvares Cabral'));
    this.tab.push(new Answers('Quelle ville a vaincu Sparte lors de la « bataille de Leuctra » ?', 'Thèbes'));
    this.tab.push(new Answers('A quelle armée appartenait la « Garde varègue » ?', 'L\'armée byzantine'));
    this.tab.push(new Answers('Lequel des commandants suivants était effectivement le dirigeant de son royaume, mais jamais officiellement le chef de l\'État ?', 'Charles Martel'));
    this.tab.push(new Answers('Lequel de ces objets ne peut PAS être acheté dans la boutique du marchand mystérieux ?', 'Passeport'));
    this.tab.push(new Answers('Combien de temps dure le boost "Basic Army Expansion" ?', '4h'));
    this.tab.push(new Answers('Quelle civilisation offre une capacité hospitalière accrue ?', 'Byzantin.'));
    this.tab.push(new Answers('Lequel d\'entre eux n\'est PAS considéré comme l\'un des "cinq bons empereurs" de la dynastie Nerva-Antonine de la Rome antique ?', 'Commode'));
    this.tab.push(new Answers('Dans quelle région était situé l\'empire de Srivijaya ?', 'Asie du sud est'));
    this.tab.push(new Answers('Qui a écrit l\'opéra Carmen ?', 'Georges Bizet'));
    this.tab.push(new Answers('Le concept de « séparation des pouvoirs » vient de quel ouvrage de Montesquieu ?', 'L\'esprit de la loi'));
    this.tab.push(new Answers('En quelle année a eu lieu la bataille de Guandu ?', '200'));
    this.tab.push(new Answers('À qui revient l\'œuvre orchestrale "Ouverture 1812" composée pour commémorer ?', 'Empire russe'));
    this.tab.push(new Answers('Dans quel pays se trouvait la Somme, le champ de bataille le plus tristement célèbre de la Première Guerre mondiale ?', 'France'));
    this.tab.push(new Answers('Qui était le chef de l\'armée occidentale lors de la bataille de Sekigahara, qui a eu lieu pendant la période Sengoku au Japon ?', 'Ishida Mitsunari'));
    this.tab.push(new Answers('Dans le Livre de l\'Exode, qui conduit le peuple juif vers la Terre Promise ?', 'Moïse'));
    this.tab.push(new Answers('Contre qui Boudica a-t-il dirigé les tribus de Grande-Bretagne dans une révolte ?', 'Le Saint Empire romain germanique'));
    this.tab.push(new Answers('De quel pays est originaire le célèbre poète Dante Alighieri ?', 'Italie'));
    this.tab.push(new Answers('Quelle est la nationalité de Pierre de Fermat, qui a proposé le dernier théorème de Fermat ?', 'France'));
    this.tab.push(new Answers('Combien d\'années s\'écoule-t-il entre chaque Jeux olympiques d\'hiver ?', '4'));
    this.tab.push(new Answers('L\'Ours d\'or est décerné dans quel festival du film ?', 'Festival du film de Berlin'));
    this.tab.push(new Answers('Lequel de ces bâtiments ne fait PAS partie des sept nouvelles merveilles du monde ?', 'Le Château de Versailles'));
    this.tab.push(new Answers('Qui a écrit la célèbre série de science-fiction "Dune"', 'Franck Herbert'));
    this.tab.push(new Answers('Quelle contribution exceptionnelle à la science a valu au biologiste Karl Landsteiner le prix Nobel ?', 'A la découverte des groupes sanguins humains'));
    this.tab.push(new Answers('Lequel de ces effets n\'est PAS causé par les compétences d\'Aethelflaed ?', 'Soigner les unités légèrement blessées'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est PAS une couleur au poker ?', 'Les vents'));
    this.tab.push(new Answers('Dans la mythologie grecque antique, qui était le père d\'Hermès ?', 'Zeus'));
    this.tab.push(new Answers('Laquelle des inventions suivantes n\'a pas vu le jour pendant la première révolution industrielle ?', 'Téléphone'));
    this.tab.push(new Answers('Qui a fondé « l\'Armada espagnole » ?', 'Philippe II'));
    this.tab.push(new Answers('Quel est l\'ingrédient principal du sel ?', 'Chlorure de sodium'));
    this.tab.push(new Answers('Qui était le professeur de Platon ?', 'Socrate'));
    this.tab.push(new Answers('L\'alphabet grec est issu de quel autre système d\'écriture ?', 'phénicien'));
    this.tab.push(new Answers('Quelle compétence active de commandant peut infliger le silence', 'Hermann'));
    this.tab.push(new Answers('Laquelle des descriptions suivantes est la description correcte de la stratosphère ?', 'Il fait chaud dessus et froid dessous'));
    this.tab.push(new Answers('Quel outil utile le célèbre charpentier Lu Ban a-t-il inventé ?', 'La scie'));
    this.tab.push(new Answers('Les pandas ont 5 orteils griffus ainsi qu\'un sixième doigt. A quoi servent les pandas avec leur sixième chiffre ?', 'Pour tenir le bambou en mangeant.'));
    this.tab.push(new Answers('Quelle est la capitale de la République du Chili ?', 'Santiago'));
    this.tab.push(new Answers('Lesquels des personnages ci-dessous n\'étaient pas des chevaliers de la table ronde du roi Arthur ?', 'Merlin'));
    this.tab.push(new Answers('Laquelle de celles-ci n\'est pas une ancienne civilisation des Amériques ?', 'Les Sumériens'));
    this.tab.push(new Answers('Combien de temps a duré la guerre de Cent Ans ?', '116 ans'));
    this.tab.push(new Answers('Quel artiste a peint la célèbre "Fille à la perle" ?', 'Jean Vermeer'));
    this.tab.push(new Answers('De quel pays est originaire Zarathoustra, du poème symphonique "Ainsi parlait Zarathoustra" ?', 'Perse'));
    this.tab.push(new Answers('Laquelle des œuvres suivantes a été écrite par le dramaturge français Pierre Corneille ?', 'Le Cid'));
    this.tab.push(new Answers('Dans la mythologie grecque antique, qui était l\'épouse d\'Hadès, le roi des enfers ?', 'Perséphone'));
    this.tab.push(new Answers('En ROK, le Hwarang est l\'unité spéciale de quelle civilisation ?', 'Corée'));
    this.tab.push(new Answers('Le dicton "L\'empire sur lequel le soleil ne se couche jamais" était à l\'origine utilisé en référence à l\'empire de quel pays ?', 'Espagne'));
    this.tab.push(new Answers('Qu\'est-ce que la technologie « Maçonnerie » peut vous aider à améliorer ?', 'La vitesse de construction des bâtiments de votre ville'));
    this.tab.push(new Answers('Lequel des éléments suivants est un bâtiment militaire ?', 'Camp scout'));
    this.tab.push(new Answers('Qui a écrit le livre bien connu « Sapiens : une brève histoire de l\'humanité » ?', 'Yuval Noé Harari'));
    this.tab.push(new Answers('D\'où vient la musique reggae ?', 'Jamaïque'));
    this.tab.push(new Answers('La civilisation phénicienne est née dans quelle partie du monde ?', 'La Méditerranée orientale'));
    this.tab.push(new Answers('Lequel de ces commandants obtient la capacité de convertir certaines unités tuées en unités grièvement blessées lors de l\'attaque d\'une ville ?', 'Charlemagne'));
    this.tab.push(new Answers('D\'après quel animal le "Tigre" est-il nommé en grec ancien ?', 'Tigre'));
    this.tab.push(new Answers('Lequel de ces pays n\'a PAS participé à la Guerre de Sept Ans du Nord (1563-1570) ?', 'Le Royaume-Uni'));
    this.tab.push(new Answers('Quelle est la plus petite espèce de serpent connue ?', 'Serpent filaire de la Barbade'));
    this.tab.push(new Answers('Qui a fondé le « sultanat de Malacca » ?', 'Parameswara'));
    this.tab.push(new Answers('Quel commandant est connu sous le nom de "The Immortal Hammer" ?', 'Charles Martel'));
    this.tab.push(new Answers('Où la bataille finale entre le roi Arthur et Mordred a-t-elle eu lieu selon la légende arthurienne ?', 'Camlann'));
    this.tab.push(new Answers('Quel commandant est surnommé « Bow of Revolution » ?', 'Yi Seong Gye'));
    this.tab.push(new Answers('Combien de troupes les gouverneurs peuvent-ils envoyer avec un hôtel de ville de niveau 17 ou supérieur ?', '4'));
    this.tab.push(new Answers('Lequel de ces officiers d\'alliance accorde un boost de vitesse de recherche ?', 'Conseiller'));
    this.tab.push(new Answers('Combien de lettres sont utilisées dans la version actuelle de l\'anglais ?', '26'));
    this.tab.push(new Answers('Laquelle des civilisations suivantes ne peut pas améliorer sa cavalerie ?', 'Les Ottomans'));
    this.tab.push(new Answers('Lequel de ces objets ne peut PAS être obtenu en battant des barbares ?', 'Points VIP'));
    this.tab.push(new Answers('En quelle année l\'Union soviétique a-t-elle été créée ?', '1922'));
    this.tab.push(new Answers('Qui a dirigé le royaume des vandales et des alains dans la guerre vandalique ?', 'Bélisaire'));
    this.tab.push(new Answers('Qui est sorti vainqueur de la « bataille de Hastings » ?', 'William le Conquérant'));
    this.tab.push(new Answers('Laquelle de ces fleurs est la fleur nationale de l\'Inde ?', 'Lotus'));
    this.tab.push(new Answers('Le "Dragonfly Cutter" était l\'arme de choix de quel guerrier légendaire ?', 'Honda Tadakatsu'));
    this.tab.push(new Answers('Qui est le patron et protecteur d\'Athènes dans la mythologie grecque antique ?', 'Athéna'));
    this.tab.push(new Answers('A qui « appartient » l\'île de Pâques ?', 'Chili'));
    this.tab.push(new Answers('Lequel des pays suivants N\'EST PAS un "pays bas" d\'Europe ?', 'Les Royaumes-Uni'));
    this.tab.push(new Answers('Qui est la mère de Cupidon, le dieu de l\'amour au visage de bébé dans la mythologie romaine ?', 'Vénus'));
    this.tab.push(new Answers('Où est né Pablo Picasso ?', 'Ibérie'));
    this.tab.push(new Answers('Quand les vélos ont-ils été introduits en Europe ?', 'Le 19ème siècle'));
    this.tab.push(new Answers('Quel commandant est réputé avoir dit « Je suis venu, j\'ai vu, j\'ai vaincu » ?', 'Jules César'));
    this.tab.push(new Answers('Quelle unité tire un fort avantage de la compétence du maître stratège de Sun Tzu ?', 'Infanterie'));
    this.tab.push(new Answers('Lequel de ces commandants obtient la capacité de convertir certaines unités tuées ?', 'Charlemagne'));
    this.tab.push(new Answers('Qui a vaincu le Sphinx selon la légende grecque ?', 'Œdipe'));
    this.tab.push(new Answers('Lequel de ces officiers d\'alliance accorde un boost de vitesse de recherche ?', 'Conseiller'));
    this.tab.push(new Answers('Qui a écrit « Humain, trop humain » ?', 'Nietzsche'));
    this.tab.push(new Answers('En République de Corée, la cataphracte est l\'unité spéciale de quelle civilisation ?', 'Byzance'));
    this.tab.push(new Answers('Où Napoléon Bonaparte a-t-il été exilé après sa défaite à Waterloo ?', 'Sainte-Hélène'));
    this.tab.push(new Answers('Quel demi-dieu capture Cerbère, le "chien à trois têtes d\'Hadès", selon la mythologie grecque ?', 'Hercule'));
    this.tab.push(new Answers('Dans quel État se trouve la Walt Disney Company ?', 'Californie'));
    this.tab.push(new Answers('Comment s\'appelle le détroit turc qui sépare l\'Europe de l\'Asie ?', 'Le Bosphore'));
    this.tab.push(new Answers('Quel est l\'élément le plus abondant de la croûte terrestre ?', 'Oxygène'));
    this.tab.push(new Answers('Qui a écrit « Le Symposium » ?', 'Platon'));
    this.tab.push(new Answers('Le chef militaire Charles Martel n\'était PAS connu pour lequel des éléments suivants ?', 'Unités de cavalerie de tête'));
    this.tab.push(new Answers('De combien de points d\'activité quotidiens avez-vous besoin dans les "Parchemins de Lucerne" pour réclamer la récompense d\'indice du cadeau quotidien ?', '50'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est PAS l\'une des compétences de Matilda of Flanders ?', 'Sang celtique'));
    this.tab.push(new Answers('Qui est le « dieu de la guerre » dans la mythologie grecque antique ?', 'Arès'));
    this.tab.push(new Answers('Quel est le plus gros animal de la planète ?', 'Baleine bleue'));
    this.tab.push(new Answers('Quand a eu lieu la Guerre de Succession d\'Autriche ?', '1740 – 1748'));
    this.tab.push(new Answers('Qui est le « dieu de la mort » dans la mythologie grecque antique ?', 'Thanatos'));
    this.tab.push(new Answers('Le Panthéon a été le lieu de sépulture de nombreux artistes importants depuis la Renaissance. Parmi les artistes suivants, lesquels y ont été enterrés ?', 'Raphaël'));
    this.tab.push(new Answers('Dans quel pays les nouilles instantanées ont-elles été inventées ?', 'Japon'));
    this.tab.push(new Answers('Quelle est la tranchée connue la plus profonde au monde ?', 'La tranchée Mariana'));
    this.tab.push(new Answers('Quelle est la plus longue chaîne de montagnes continentale sur terre ?', 'Les Andes'));
    this.tab.push(new Answers('Laquelle des technologies suivantes précède "l\'équitation" ?', 'Discipline militaire'));
    this.tab.push(new Answers('Quel commandant militaire était connu sous le nom de « Libérateur de Teutoburg » ?', 'Hermann'));
    this.tab.push(new Answers('Quelle est la mesure d\'une année-lumière ?', 'Distance'));
    this.tab.push(new Answers('Le colosse de Rhodes représente quel dieu du soleil ?', 'Hélios'));
    this.tab.push(new Answers('Quel compositeur a écrit l\'opéra "L\'anneau du Nibelung" ?', 'wagner'));
    this.tab.push(new Answers('Quel était le but initial de la Grande Pyramide de Gizeh ?', 'La tombe du pharaon Khéops'));
    this.tab.push(new Answers('Quel est le surnom de Jules César ?', 'Le roi sans couronne'));
    this.tab.push(new Answers('Qui a conçu le « canon ottoman » ?', 'Urbain'));
    this.tab.push(new Answers('Quel pays combattait l\'Angleterre lors de la bataille d\'Azincourt ?', 'France'));
    this.tab.push(new Answers('Qu\'est-ce que Che Guevara a étudié à l\'université?', 'Médecine'));
    this.tab.push(new Answers('Qui est responsable de l\'introduction de vaillants guerriers dans le Valhalla à leur mort dans la mythologie nordique ?', 'Walkyrie'));
    this.tab.push(new Answers('Qui a écrit le livre bien connu « Une brève histoire du temps » ?', 'Stephen Hawking'));
    this.tab.push(new Answers('Lequel de ces prix Nobel a été décerné à Marie Curie en 1903 ?', 'Le prix Nobel de physique'));
    this.tab.push(new Answers('Lequel de ces pays N\'EST PAS membre fondateur de l\'OTAN (en 1949) ?', 'Turquie'));
    this.tab.push(new Answers('Laquelle de ces œuvres de la littérature monogatari japonaise décrit la légende de « Kaguya-hime » ?', 'L\'histoire du coupeur de bambou'));
    this.tab.push(new Answers('Laquelle des compétences suivantes ne fait PAS partie des compétences de Baybar ?', 'Force tonitruante'));
    this.tab.push(new Answers('La "Journée des Tuiles" est considérée par certains historiens comme marquant le début de la Révolution française. Dans quelle ville a-t-il eu lieu ?', 'Grenoble'));
    this.tab.push(new Answers('Quel avantage la recherche en « mathématiques » à l\'Académie offre-t-elle ?', 'Vitesse de recherche accrue'));
    this.tab.push(new Answers('Qui était le premier consul de la République romaine ?', 'Lucius Junius Brutus'));
    this.tab.push(new Answers('Quel continent a été le berceau de la civilisation maya ?', 'Les Amériques'));
    this.tab.push(new Answers('Qui a dirigé le royaume de Prusse pendant la guerre de Sept Ans ?', 'Frédéric II'));
    this.tab.push(new Answers('Quel musicien a composé « Les Noces de Figaro » ?', 'Mozart'));
    this.tab.push(new Answers('Les hiéroglyphes faisaient partie du système d\'écriture formel de quel pays ?', 'L\'Egypte ancienne'));
    this.tab.push(new Answers('Laquelle de ces compétences est l\'une des "compétences actives" de Minamoto no Yoshitune ?', 'Kyohachiryu'));
    this.tab.push(new Answers('Quel commandant est généralement considéré comme ayant illustré l\'idéal de « l\'esprit Bushido » ?', 'Kusunoki Masashige'));
    this.tab.push(new Answers('Quel ancien tombeau de pharaon égyptien l\'archéologue britannique Howard Carter a-t-il découvert en 1992 ?', 'Toutankhamon'));
    this.tab.push(new Answers('À quelle fréquence la Coupe du monde de football a-t-elle lieu ?', 'Tous les 4 ans'));
    this.tab.push(new Answers('La reine Guenièvre est tombée amoureuse de quel chevalier de la table ronde selon la légende arthurienne ?', 'Lancelot'));
    this.tab.push(new Answers('Les épines de cactus sont en fait une forme modifiée de quelle autre partie de la plante ?', 'Feuilles'));
    this.tab.push(new Answers('Les équipements avec des bonus de talent spéciaux verront leurs attributs améliorés de quel pourcentage lorsqu\'ils seront équipés pour un commandant avec le talent correspondant ?', '0,3'));
    this.tab.push(new Answers('Lequel de ces artistes n\'était PAS un peintre de la Baraque ?', 'Vincent Van Gogh'));
    this.tab.push(new Answers('Les coffres de réussite à 1 000 points comprennent :', 'Sculpture de commandant épique'));
    this.tab.push(new Answers('« Machu Picchu » est une relique remarquable de quelle civilisation ?', 'Les Incas'));
    this.tab.push(new Answers('Quel artiste est enterré au Panthéon ?', 'Raphaël'));
    this.tab.push(new Answers('Qui tue Odin, le roi des dieux, lors du Ragnarok dans la mythologie nordique ?', 'Fenrir'));
    this.tab.push(new Answers('Combien d\'objets de même qualité dois-je équiper pour terminer "Prêt pour la bataille" ?', '6'));
    this.tab.push(new Answers('Dans la page Commander View, quel buff les commandants agissant en tant que "Bloodfist Guard" obtiennent-ils ?', '1% Santé des troupes'));
    this.tab.push(new Answers('Dans quel pays la « bataille de Marengo » a-t-elle eu lieu ?', 'Italie'));
    this.tab.push(new Answers('Quel empereur a été nommé le "Khan du Ciel" par divers nomades turcs pendant les dynasties Sui et Tang ?', 'Empereur Taizong des Tang'));
    this.tab.push(new Answers('La « bataille de Las Na﻿vas de Tolosa » a été un tournant majeur dans quel conflit ?', 'La Reconquête'));
    this.tab.push(new Answers('Qui a fondé le premier empire perse ?', 'Cyrus le Grand'));
    this.tab.push(new Answers('À quelle époque de l\'histoire chinoise la « bataille de la rivière Fei » a-t-elle eu lieu où un petit nombre de soldats ont conquis une force largement supérieure ?', 'La dynastie des Jin de l\'Est'));
    this.tab.push(new Answers('Quelle race de créatures, mythiques ou non, vivait sur Asgard selon le mythe nordique ?', 'Ases'));
    this.tab.push(new Answers('La crise du détroit turc divise l\'Europe et l\'Asie', 'Bosphore'));
    this.tab.push(new Answers('Qui a fondé le shogunat de Kamakura ?', 'Minamoto no Yoritomo'));
    this.tab.push(new Answers('Lequel des éléments suivants n\'est pas l\'un des destins de la mythologie nordique ?', 'Karma'));
    this.tab.push(new Answers('L\'épopée "Poème d\'El Cid" est originaire de quel pays ?', 'Espagne'));
    this.tab.push(new Answers('Le commandant légendaire de la dynastie Joseon, Yi Sun-sin, a sacrifié sa vie dans quelle célèbre bataille ?', 'Bataille de Noryang'));
    this.tab.push(new Answers('Laquelle de ces descriptions est une description incorrecte de la « bataille de Poitiers » ?', 'La campagne a eu lieu pendant la Première Guerre mondiale'));
    this.tab.push(new Answers('Laquelle de ces descriptions est une description incorrecte de la "Mare Imbrium" sur la lune ?', 'Il contient une certaine quantité d\'eau sédimentaire'));
    this.tab.push(new Answers('Qui est le premier Italien à recevoir le « Pritzker Architecture Prize » ?', 'Aldo Rossi'));
    this.tab.push(new Answers('Comment s\'appelle le détroit turc qui sépare l\'Europe de l\'Asie ?', 'Le détroit de Gibraltar'));
    this.tab.push(new Answers('Qui a fondé le "Sultanat de Malacca" ?', 'Parameswara'));
    this.filteredTab = this.tab;
  }

  changeSearchValue(): void {
    if (this.searchValue.length === 0) {
      this.filteredTab = this.tab;
    } else {
      this.filteredTab = [];
      const keywords = this.searchValue.toLocaleLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').split(' ').filter((val: string) => {
        return val.trim().length > 0;
      });
      this.filteredTab = this.tab.filter(e => {
        let counter = 0;
        keywords.forEach((keyword: string) => {
          if(e.questionNormalized?.includes(keyword)){
            counter++;
          }
        });
        return counter == keywords.length;
      });
    }
  }
}

